default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: waldo_dev
  username: diti      # your WSL/local PostgreSQL username
  password: Deepthi901       # your WSL/local PostgreSQL password (empty if none)
  host: localhost

test:
  <<: *default
  database: waldo_test
  username: diti
  password: Deepthi901
  host: localhost

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  # Neon connection string goes in the environment variable DATABASE_URL
